### ISSUE TITLE
The main difference between the two methods, getErrorStatus() and getErrorsOccurred(), is the type of information they provide and how it can be used in an application.

### ISSUE THREAD

**Issue by yasir-shahzad** [pololu/tic-arduino#3]

**Comment by DavidEGrayson** [comment]
I'm not sure what kind of response you are looking for, since you did not ask a question or a describe a problem.  We use GitHub issues to discuss specific problems with the code or feature requests.  If you need help with the Tic, I suggest rephrasing your question and posting on our forum:

https://forum.pololu.com/c/support/pololu-motor-controllers-drivers-and-motors/19
